inputs:

{ config, lib, pkgs, ... }:

let
  inherit (lib) mkEnableOption mkOption types mkIf mkDefault;
  cfg = config.programs.illogical-impulse;

  # Use dotfiles from flake input
  dotfilesSource = inputs.dotfiles;

  # Custom packages
  customPkgs = import ../pkgs { inherit pkgs; };
  oneUIIconsPath = "${customPkgs.illogical-impulse-oneui4-icons}/share/icons";
in
{
  options.programs.illogical-impulse.dotfiles = {
    fish.enable = mkEnableOption "Use the Illogical Impulse fish config" // { default = true; };
    kitty.enable = mkEnableOption "Install kitty and use the Illogical Impulse kitty config" // { default = true; };
    starship.enable = mkEnableOption "Install starship and use the Illogical Impulse prompt" // { default = true; };
  };

  options.programs.illogical-impulse.hyprland = {
    plugins = mkOption {
      type = types.listOf types.package;
      default = [];
      description = "List of Hyprland plugins to install and load";
    };
  };

  config = mkIf cfg.enable {
    # Fake venv for QuickShell scripts to use the Nix python environment
    home.file = {
      ".local/state/quickshell/.venv/bin/activate".text = ''
        # Generated by Illogical Impulse Flake
        export VIRTUAL_ENV="${config.programs.illogical-impulse.internal.pythonEnv}"
        export PATH="${config.programs.illogical-impulse.internal.pythonEnv}/bin:$PATH"
        deactivate () {
            # Dummy function for compatibility
            return 0
        }
      '';
      ".local/state/quickshell/.venv/bin/python".source = "${config.programs.illogical-impulse.internal.pythonEnv}/bin/python";
      ".local/state/quickshell/.venv/bin/python3".source = "${config.programs.illogical-impulse.internal.pythonEnv}/bin/python3";
      ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
        home = ${config.programs.illogical-impulse.internal.pythonEnv}/bin
        include-system-site-packages = false
        version = 3.11.0
      '';
    };

    # Install the plugins to the user environment so they are available
    home.packages = cfg.hyprland.plugins;

    # Shell programs
    programs.fish = {
      enable = cfg.dotfiles.fish.enable;
      interactiveShellInit = ''
        if test -f ${config.xdg.configHome}/fish/config-custom.fish
          source ${config.xdg.configHome}/fish/config-custom.fish
        end
      '';
    };
    programs.starship.enable = cfg.dotfiles.starship.enable;

    # Symlink standard icon themes (Adwaita)
    home.file.".local/share/icons/Adwaita".source = "${pkgs.adwaita-icon-theme}/share/icons/Adwaita";

    # Configure icon theme for GTK and Qt applications
    gtk = {
      enable = mkDefault true;
      iconTheme = {
        name = mkDefault "OneUI-dark";
        package = mkDefault customPkgs.illogical-impulse-oneui4-icons;
      };
    };

    # Set icon theme via dconf for GNOME/GTK apps
    dconf.settings = {
      "org/gnome/desktop/interface" = {
        icon-theme = mkDefault "OneUI-dark";
      };
    };

    # Dotfiles management via Home Manager (XDG Config)
    xdg.configFile = {
      "chrome-flags.conf".source = "${dotfilesSource}/dots/.config/chrome-flags.conf";
      "code-flags.conf".source = "${dotfilesSource}/dots/.config/code-flags.conf";
      "darklyrc".source = "${dotfilesSource}/dots/.config/darklyrc";
      "dolphinrc".source = "${dotfilesSource}/dots/.config/dolphinrc";
      "foot".source = "${dotfilesSource}/dots/.config/foot";
      "fuzzel".source = "${dotfilesSource}/dots/.config/fuzzel";
      
      # Hyprland Config
      # Use text/readFile to put the file in the HM generation directory
      # This ensures relative sources (like hyprland/env.conf) resolve to OUR patched files
      "hypr/hyprland.conf".text = (builtins.readFile "${dotfilesSource}/dots/.config/hypr/hyprland.conf") + ''
        
        # Load declarative plugins from the flake
        source = plugins.conf
      '';
      
      # Generate plugins.conf with paths to installed plugins
      "hypr/plugins.conf".text = lib.concatMapStrings (plugin: ''
        plugin = ${plugin}/lib/lib${plugin.pname}.so
      '') cfg.hyprland.plugins;
      
      # Hyprland Environment - Patched to fix XDG_DATA_DIRS and define qsConfig EARLY
      "hypr/hyprland/env.conf".text = ''
        # --- Injected Environment by Illogical Impulse Flake ---
        env = PATH,${config.home.homeDirectory}/.nix-profile/bin:/etc/profiles/per-user/${config.home.username}/bin:$PATH
        env = XDG_DATA_DIRS,${config.home.homeDirectory}/.nix-profile/share:${config.home.homeDirectory}/.local/share:/etc/profiles/per-user/${config.home.username}/share:/run/current-system/sw/share:${config.home.homeDirectory}/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:$XDG_DATA_DIRS
        env = QT_PLUGIN_PATH,${config.home.homeDirectory}/.nix-profile/lib/qt-6/plugins:${config.home.homeDirectory}/.nix-profile/lib/plugins
        env = QML2_IMPORT_PATH,${config.home.homeDirectory}/.nix-profile/lib/qt-6/qml
        env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
        env = QT_QPA_PLATFORMTHEME,gtk3
        
        # Define qsConfig for exec-once commands
        $qsConfig = ${config.home.homeDirectory}/.config/quickshell/ii
        env = qsConfig,${config.home.homeDirectory}/.config/quickshell/ii

        # --- Original Environment Content ---
        env = ELECTRON_OZONE_PLATFORM_HINT,auto
        env = QT_QPA_PLATFORM, wayland
        env = XDG_MENU_PREFIX, plasma-
        env = ILLOGICAL_IMPULSE_VIRTUAL_ENV, ~/.local/state/quickshell/.venv
        env = TERMINAL,kitty -1
      '';

      # Symlink other hyprland files individually
      "hypr/hyprland/colors.conf".source = "${dotfilesSource}/dots/.config/hypr/hyprland/colors.conf";
      "hypr/hyprland/execs.conf".source = "${dotfilesSource}/dots/.config/hypr/hyprland/execs.conf";
      # Patch general.conf to remove obsolete hyprexpo options (enable_gesture, gesture_positive)
      # These were removed from the hyprexpo plugin API and cause "Invalid value false for finger count" error
      "hypr/hyprland/general.conf".text = builtins.replaceStrings
        [ "enable_gesture = false" "gesture_positive = false" ]
        [ "# enable_gesture = false  # Removed: obsolete hyprexpo option" "# gesture_positive = false  # Removed: obsolete hyprexpo option" ]
        (builtins.readFile "${dotfilesSource}/dots/.config/hypr/hyprland/general.conf");
      "hypr/hyprland/keybinds.conf".source = "${dotfilesSource}/dots/.config/hypr/hyprland/keybinds.conf";
      "hypr/hyprland/rules.conf".source = "${dotfilesSource}/dots/.config/hypr/hyprland/rules.conf";
      "hypr/hyprland/scripts".source = "${dotfilesSource}/dots/.config/hypr/hyprland/scripts";

      # Hyprland Custom Env - Reverted to direct source
      "hypr/custom/env.conf".source = "${dotfilesSource}/dots/.config/hypr/custom/env.conf";

      # Symlink custom siblings
      "hypr/custom/execs.conf".source = "${dotfilesSource}/dots/.config/hypr/custom/execs.conf";
      "hypr/custom/general.conf".source = "${dotfilesSource}/dots/.config/hypr/custom/general.conf";
      "hypr/custom/keybinds.conf".source = "${dotfilesSource}/dots/.config/hypr/custom/keybinds.conf";
      "hypr/custom/rules.conf".source = "${dotfilesSource}/dots/.config/hypr/custom/rules.conf";
      "hypr/custom/scripts".source = "${dotfilesSource}/dots/.config/hypr/custom/scripts";
      "hypr/hyprlock".source = "${dotfilesSource}/dots/.config/hypr/hyprlock";
      "hypr/hypridle.conf".source = "${dotfilesSource}/dots/.config/hypr/hypridle.conf";
      "hypr/hyprlock.conf".source = "${dotfilesSource}/dots/.config/hypr/hyprlock.conf";
      "hypr/monitors.conf".source = "${dotfilesSource}/dots/.config/hypr/monitors.conf";
      "hypr/workspaces.conf".source = "${dotfilesSource}/dots/.config/hypr/workspaces.conf";

      # kdeglobals handled in activation script
      # "kdeglobals".source = "${dotfilesSource}/dots/.config/kdeglobals";
      
      "kde-material-you-colors".source = "${dotfilesSource}/dots/.config/kde-material-you-colors";
      "kitty".source = "${dotfilesSource}/dots/.config/kitty";
      "konsolerc".source = "${dotfilesSource}/dots/.config/konsolerc";
      "Kvantum".source = "${dotfilesSource}/dots/.config/Kvantum";
      "matugen".source = "${dotfilesSource}/dots/.config/matugen";
      "mpv".source = "${dotfilesSource}/dots/.config/mpv";
      
      # Patch QuickShell scripts to fix shebangs (e.g., #!/bin/bash -> #!/nix/store/.../bash)
      "quickshell".source = pkgs.runCommand "quickshell-patched" { 
        buildInputs = [ 
          pkgs.bash 
          config.programs.illogical-impulse.internal.pythonEnv 
        ]; 
      } ''
        cp -r ${dotfilesSource}/dots/.config/quickshell $out
        chmod -R +w $out
        
        # Replace complex shebangs that patchShebangs can't handle with standard python
        # The complex shebang tried to source a venv, but we provide pythonEnv directly via Nix
        find $out -name "*.py" -print0 | xargs -0 sed -i 's|^#!.*ILLOGICAL_IMPULSE_VIRTUAL_ENV.*|#!/usr/bin/env python3|'
        
        # Suppress permission errors when writing to /dev/pts in applycolor.sh
        sed -i 's|/dev/pts/\*|/dev/pts/* 2>/dev/null|' $out/ii/scripts/colors/applycolor.sh

        patchShebangs $out
      '';

      "starship.toml".source = "${dotfilesSource}/dots/.config/starship.toml";
      "thorium-flags.conf".source = "${dotfilesSource}/dots/.config/thorium-flags.conf";
      "wlogout".source = "${dotfilesSource}/dots/.config/wlogout";
      "xdg-desktop-portal".source = "${dotfilesSource}/dots/.config/xdg-desktop-portal";
      "zshrc.d".source = "${dotfilesSource}/dots/.config/zshrc.d";

      # Fontconfig wrapper to ensure system fonts are loaded
      "fontconfig/fonts.conf".text = ''
        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
        <fontconfig>
            <include ignore_missing="yes">/etc/fonts/fonts.conf</include>
            <match target="font">
                <edit name="rgba" mode="assign">
                <const>none</const>
            </edit>
          </match>
        </fontconfig>
      '';
      
      # Fish config (custom integration)
      "fish/config-custom.fish" = mkIf cfg.dotfiles.fish.enable {
        source = "${dotfilesSource}/dots/.config/fish/config.fish";
      };
      "fish/auto-Hypr.fish" = mkIf cfg.dotfiles.fish.enable {
        source = "${dotfilesSource}/dots/.config/fish/auto-Hypr.fish";
      };
    };

    # Dotfiles management via Home Manager (XDG Data)
    xdg.dataFile = {
      # Note: Icons are installed via packages (illogical-impulse-oneui4-icons) 
      # and the custom icon is handled here if needed, but it's usually in the package too?
      # Re-adding the single SVG manually just in case
      "icons/hicolor/scalable/apps/illogical-impulse.svg".source = "${dotfilesSource}/dots/.local/share/icons/illogical-impulse.svg";
    };

    # Use activation script ONLY for stateful integration
    home.activation.copyIllogicalImpulseConfigs = config.lib.dag.entryAfter ["writeBoundary"] ''
      # Path to the config directory in the dotfiles source
      configPath="${dotfilesSource}/dots/.config"
      targetPath="$HOME/.config"

      # Create illogical-impulse directory structure if it doesn't exist (Stateful config)
      $DRY_RUN_CMD mkdir -p "$targetPath/illogical-impulse"

      # Copy the default config.json only if it doesn't already exist
      if [ ! -f "$targetPath/illogical-impulse/config.json" ]; then
        if [ -f "$configPath/illogical-impulse/config.json" ]; then
          $DRY_RUN_CMD cp "$configPath/illogical-impulse/config.json" "$targetPath/illogical-impulse/config.json"
          $DRY_RUN_CMD chmod u+w "$targetPath/illogical-impulse/config.json"
        fi
      fi
      
      # Handle kdeglobals (Mutable copy)
      # If it's a symlink (likely from previous HM generation), remove it first
      if [ -L "$targetPath/kdeglobals" ]; then
          $DRY_RUN_CMD rm "$targetPath/kdeglobals"
      fi

      # We copy it if it doesn't exist (or was just removed), to allow scripts to modify it
      if [ ! -f "$targetPath/kdeglobals" ]; then
         if [ -f "$configPath/kdeglobals" ]; then
             $DRY_RUN_CMD cp "$configPath/kdeglobals" "$targetPath/kdeglobals"
             $DRY_RUN_CMD chmod u+w "$targetPath/kdeglobals"
         fi
      else
         # Ensure it's writable even if it exists
         $DRY_RUN_CMD chmod u+w "$targetPath/kdeglobals"
      fi

      # Handle konsole directory (Mutable directory with managed files)
      konsoleTarget="$HOME/.local/share/konsole"
      konsoleSource="${dotfilesSource}/dots/.local/share/konsole"

      # If it is a symlink (from previous HM generation), remove it
      if [ -L "$konsoleTarget" ]; then
          $DRY_RUN_CMD rm "$konsoleTarget"
      fi

      # Ensure directory exists
      if [ ! -d "$konsoleTarget" ]; then
          $DRY_RUN_CMD mkdir -p "$konsoleTarget"
      fi

      # Sync files (copy managed files into the mutable directory and make writable)
      for file in "$konsoleSource"/*; do
          filename=$(basename "$file")
          # Copy (force overwrite) instead of symlink so the file itself is mutable
          # Use rm first to avoid "same file" errors if it was a hardlink or symlink previously
          if [ -e "$konsoleTarget/$filename" ]; then
              $DRY_RUN_CMD rm -f "$konsoleTarget/$filename"
          fi
          $DRY_RUN_CMD cp "$file" "$konsoleTarget/$filename"
          $DRY_RUN_CMD chmod u+w "$konsoleTarget/$filename"
      done

      # Fix Qt icon theme configuration to use OneUI-dark/OneUI-light with Papirus fallback
      # This is still needed because qt6ct might be generating its config
      for qt_conf in "$targetPath/qt5ct/qt5ct.conf" "$targetPath/qt6ct/qt6ct.conf"; do
        if [ -f "$qt_conf" ]; then
          # Replace OneUI with OneUI-dark, OneUI-light stays as-is
          $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI$/icon_theme=OneUI-dark/' "$qt_conf"
          $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI-light$/icon_theme=OneUI-light/' "$qt_conf"
        fi
      done
    '';
  };
}